version: "3.9"

volumes:
  postgres_data: {}

services:
  app: &app
    build:
      context: .
      dockerfile: ./compose/django/Dockerfile
    image: metro_django
    depends_on:
    - db
    volumes:
    - .:/app
    env_file:
    - ./.env/.django
    - ./.env/.postgres
    ports:
    - "8000:8000"
    command: /start

  db:
   image: postgres
   volumes:
     - postgres_data:/var/lib/postgresql/data
   env_file:
     - ./.env/.postgres

  redis:
    image: redis:3.2

  celeryworker:
    <<: *app
    image: metro_celeryworker
    depends_on:
      - redis
      - db
      
    ports: []
    command: /start-celeryworker

  celerybeat:
    <<: *app
    image: metro_celerybeat
    depends_on:
      - redis
      - db
      
    ports: []
    command: /start-celerybeat
