# Generated by Django 4.0.4 on 2022-05-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_unit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
