# Generated by Django 4.0.4 on 2022-05-15 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_unit_id'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Township',
            new_name='District',
        ),
        migrations.RenameField(
            model_name='unit',
            old_name='township',
            new_name='district',
        ),
    ]
